version: 2.1

jobs:
  test:
    working_directory: ~/transformers
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Type Checking
          command: |
                  pipenv install --dev --ignore-pipfile
                  pipenv run python -m mypy ./tests --config-file ./mypy.ini
                  pipenv run python -m mypy ./transformers --config-file ./mypy.ini
      - run:
          name: Unit Tests
          command: |
                  mkdir ./tests/results
                  pipenv run python -m pytest --junitxml=./tests/results/results.xml
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ./tests
          
  build:
    working_directory: ~/transformers
    docker: 
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Build Wheel
          command: |
            pipenv run python setup.py bdist_wheel
            git push add -A
            git commit -m 'Updated by CircleCI [ci skip]'
            git push origin master

workflows:
  main:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master