version: 2.1

jobs:
  test:
    working_directory: ~/transformers
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Type Checking
          command: |
                  pipenv install --dev --ignore-pipfile
                  pipenv run python -m mypy ./tests --config-file ./mypy.ini
                  pipenv run python -m mypy ./transformers --config-file ./mypy.ini
      - run:
          name: Unit Tests
          command: |
                  mkdir ./tests/results
                  pipenv run python -m pytest --junitxml=./tests/results/results.xml
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ./tests
          
  build:
    working_directory: ~/transformers
    docker: 
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ef:33:92:19:50:52:0d:60:02:d5:05:fe:ee:d3:c4:68"
      - run:
          name: Build wheel
          command: |
            pipenv run python3 setup.py bdist_wheel
      - run:
          name: Push wheel
          command: |
            git config user.email "carter.marshall@gmail.com"
            git config user.name “marshackVB”
            git add -A
            git commit -m 'updated by CircleCI [ci skip]'
            git push -q origin master

workflows:
  main:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master