version: 2.1

defaults: &defaults
  working_directory: ~/transformers
  docker: 
    - image: circleci/python:3.7.4
      environment:
        PIPENV_VENV_IN_PROJECT: true
  
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Type Checking
          command: |
                  pipenv install --dev --ignore-pipfile
                  pipenv run python -m mypy ./tests --config-file ./mypy.ini
                  pipenv run python -m mypy ./transformers --config-file ./mypy.ini
      - run:
          name: Unit Tests
          command: |
                  mkdir ./tests/results
                  pipenv run python -m pytest --junitxml=./tests/results/results.xml
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ../
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ../
          destination: tr1
          
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Wheel
          command: |
            python3 setup.py bdist_wheel

workflows:
  main:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master